/**
 * A flight companion, served at /fly/<aircraft>.
 *
 * Each companion is a standalone page rather than a route in the printer
 * shell, so the markup is kept as one plain HTML template and filled in per
 * aircraft. Going through an endpoint (instead of dropping files in static/)
 * gives the URLs something the prerenderer and the link crawler can resolve.
 *
 * The checklist payload is generated by scripts/build-companion.mjs (pnpm fly)
 * and injected here at build time, so each page ships self-contained and loads
 * without a second request. The generator writes bare JSON; escapeJson below is
 * the only place "</" is escaped, so it must not be done twice.
 */
import { error } from "@sveltejs/kit";
import template from "$lib/fly/companion.html?raw";
import fbwA32nx from "$lib/fly/fbw-a32nx.json";
import { aircraft, type AircraftSlug } from "../../../params/aircraft";
import type { EntryGenerator, RequestHandler } from "./$types";

/** One payload per aircraft. The Record makes the compiler ask for it. */
const payloads: Record<AircraftSlug, unknown> = {
  "fbw-a32nx": fbwA32nx,
};

export const prerender = true;

export const entries: EntryGenerator = () =>
  aircraft.map((entry) => ({ aircraft: entry.slug }));

const escapeHtml = (value: string) =>
  value.replace(
    /[&<>"]/g,
    (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[char]!,
  );

// Inside a <script type="application/json"> block, only "</" needs escaping.
const escapeJson = (value: unknown) =>
  JSON.stringify(value).replace(/<\//g, "<\\/");

/** Built once at startup: there are only ever a handful of aircraft. */
const pages = new Map<string, string>(
  aircraft.map((entry) => [
    entry.slug,
    template
      .replaceAll("%name%", escapeHtml(entry.name))
      .replaceAll("%slug%", entry.slug)
      .replace("/*__DATA__*/", () => escapeJson(payloads[entry.slug])),
  ]),
);

export const GET: RequestHandler = ({ params }) => {
  const page = pages.get(params.aircraft);
  if (!page) error(404, "Unknown aircraft");

  return new Response(page, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
};
